### ISSUE TITLE
tx.search on 7179486 block generates KeyError exception

### ISSUE THREAD

**Issue by cscsabai** [terra-money/terra.py#101]
- terra_sdk version: 2.0.5
- Python version:3.8.9
- Operating System: macOS

### Description

terra.tx.search generates KeyError exception on 7179486 block.

### What I Did

```
from terra_sdk.client.lcd import LCDClient, PaginationOptions
terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")
terra.tx.search([("tx.height", 7179486)])
```

result:

```
>>> terra.tx.search([("tx.height", 7179486)])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 29, in decorator
    return instance._run_sync(async_call(instance, *args, **kwargs))
  File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 13, in _run_sync
    return self._c.loop.run_until_complete(coroutine)
  File ".../lib/python3.8/site-packages/nest_asyncio.py", line 89, in run_until_complete
    return f.result()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/tx.py", line 356, in search
    "txs": [TxInfo.from_data(tx) for tx in res.get("tx_responses")],
  File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/tx.py", line 356, in <listcomp>
    "txs": [TxInfo.from_data(tx) for tx in res.get("tx_responses")],
  File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 456, in from_data
    Tx.from_data(data["tx"]),
  File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 87, in from_data
    TxBody.from_data(data["body"]),
  File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 184, in from_data
    [Msg.from_data(m) for m in data["messages"]],
  File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 184, in <listcomp>
    [Msg.from_data(m) for m in data["messages"]],
  File ".../lib/python3.8/site-packages/terra_sdk/core/msg.py", line 19, in from_data
    return parse_msg(data)
  File ".../lib/python3.8/site-packages/terra_sdk/util/base.py", line 27, in from_data
    return table[data["@type"]](data)
  File ".../lib/python3.8/site-packages/terra_sdk/core/authz/msgs.py", line 116, in from_data
    data = data["value"]
KeyError: 'value'

```

**Comment by Charlotte61** [comment]
> * terra_sdk version: 2.0.5
> * Python version:3.8.9
> * Operating System: macOS
> 
> ### Description
> terra.tx.search generates KeyError exception on 7179486 block.
> 
> ### What I Did
> ```
> from terra_sdk.client.lcd import LCDClient, PaginationOptions
> terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")
> terra.tx.search([("tx.height", 7179486)])
> ```
> 
> result:
> 
> ```
> >>> terra.tx.search([("tx.height", 7179486)])
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 29, in decorator
>     return instance._run_sync(async_call(instance, *args, **kwargs))
>   File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 13, in _run_sync
>     return self._c.loop.run_until_complete(coroutine)
>   File ".../lib/python3.8/site-packages/nest_asyncio.py", line 89, in run_until_complete
>     return f.result()
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/futures.py", line 178, in result
>     raise self._exception
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 280, in __step
>     result = coro.send(None)
>   File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/tx.py", line 356, in search
>     "txs": [TxInfo.from_data(tx) for tx in res.get("tx_responses")],
>   File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/tx.py", line 356, in <listcomp>
>     "txs": [TxInfo.from_data(tx) for tx in res.get("tx_responses")],
>   File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 456, in from_data
>     Tx.from_data(data["tx"]),
>   File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 87, in from_data
>     TxBody.from_data(data["body"]),
>   File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 184, in from_data
>     [Msg.from_data(m) for m in data["messages"]],
>   File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 184, in <listcomp>
>     [Msg.from_data(m) for m in data["messages"]],
>   File ".../lib/python3.8/site-packages/terra_sdk/core/msg.py", line 19, in from_data
>     return parse_msg(data)
>   File ".../lib/python3.8/site-packages/terra_sdk/util/base.py", line 27, in from_data
>     return table[data["@type"]](data)
>   File ".../lib/python3.8/site-packages/terra_sdk/core/authz/msgs.py", line 116, in from_data
>     data = data["value"]
> KeyError: 'value'
> ```

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)

**Comment by Charlotte61** [comment]
> * terra_sdk version: 2.0.5
> * Python version:3.8.9
> * Operating System: macOS
> 
> ### Description
> terra.tx.search generates KeyError exception on 7179486 block.
> 
> ### What I Did
> ```
> from terra_sdk.client.lcd import LCDClient, PaginationOptions
> terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")
> terra.tx.search([("tx.height", 7179486)])
> ```
> 
> result:
> 
> ```
> >>> terra.tx.search([("tx.height", 7179486)])
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 29, in decorator
>     return instance._run_sync(async_call(instance, *args, **kwargs))
>   File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/_base.py", line 13, in _run_sync
>     return self._c.loop.run_until_complete(coroutine)
>   File ".../lib/python3.8/site-packages/nest_asyncio.py", line 89, in run_until_complete
>     return f.result()
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/futures.py", line 178, in result
>     raise self._exception
>   File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/asyncio/tasks.py", line 280, in __step
>     result = coro.send(None)
>   File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/tx.py", line 356, in search
>     "txs": [TxInfo.from_data(tx) for tx in res.get("tx_responses")],
>   File ".../lib/python3.8/site-packages/terra_sdk/client/lcd/api/tx.py", line 356, in <listcomp>
>     "txs": [TxInfo.from_data(tx) for tx in res.get("tx_responses")],
>   File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 456, in from_data
>     Tx.from_data(data["tx"]),
>   File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 87, in from_data
>     TxBody.from_data(data["body"]),
>   File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 184, in from_data
>     [Msg.from_data(m) for m in data["messages"]],
>   File ".../lib/python3.8/site-packages/terra_sdk/core/tx.py", line 184, in <listcomp>
>     [Msg.from_data(m) for m in data["messages"]],
>   File ".../lib/python3.8/site-packages/terra_sdk/core/msg.py", line 19, in from_data
>     return parse_msg(data)
>   File ".../lib/python3.8/site-packages/terra_sdk/util/base.py", line 27, in from_data
>     return table[data["@type"]](data)
>   File ".../lib/python3.8/site-packages/terra_sdk/core/authz/msgs.py", line 116, in from_data
>     data = data["value"]
> KeyError: 'value'
> ```

Hello, A support ticket has been opened for you with Support ticket number TB7196HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)
