### ISSUE TITLE
How can set memo in MsgMultiSend for every output?

### ISSUE THREAD

**Issue by SheydaAshoorian** [terra-money/terra.py#104]
- terra_sdk version:2.0.4 
- Python version:3.10
- Operating System:macOs

In batch transaction I want to set memo for every transaction. how can I do? is it possible or not?

**Comment by Vritra4** [comment]
you mean you want to set memo in the MsgMultiSend, not in a tx? it is not available.
msgs have no memo, only txs do.

**Comment by SheydaAshoorian** [comment]
> 

@Vritra4 thanks. yes I do , I wanted to use memo for MsgMultiSend

**Comment by bridget432** [comment]
hi @SheydaAshoorian yes you can set up memo, I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum [——>>  [TERRA DEVELOPERS LIVE CHAT](https://agora.terras.live/) To help you sort this out right away
