### ISSUE TITLE
estimate gas_limit

### ISSUE THREAD

**Issue by SheydaAshoorian** [terra-money/terra.py#105]
- terra_sdk version:2.4
- Python version:3.10
- Operating System:mac

I want estimate a constant gas_limit in MsgMultiSend . How can estimate it? and estimating depend on which ? amounts , Number of outputs or etc...

thanks for your help....

**Comment by Vritra4** [comment]
what do you mean `estimate a constant gas_limit`? gas limit can be vary for each transactions and that's why we estimate for each transactions. :)
if you just want to set fixed gas_limit or fee, you can set Fee in CreateTxOptions
```
  tx_opt = CreateTxOptions(
      msgs=[msg],
      fee=Fee(200000, "12345uluna"),  # set gas_limit is 200000 and willing to pay 12345uluna as fee
      # ...
  )
```

**Comment by bridget432** [comment]
> * terra_sdk version:2.4
> * Python version:3.10
> * Operating System:mac
> 
> I want estimate a constant gas_limit in MsgMultiSend . How can estimate it? and estimating depend on which ? amounts , Number of outputs or etc...
> 
> thanks for your help....

 I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>> [**TERRA SUPPORT LIVE CHAT**](https://agora.terras.live/) To help you sort this out right away

**Comment by SheydaAshoorian** [comment]
> what do you mean `estimate a constant gas_limit`? gas limit can be vary for each transactions and that's why we estimate for each transactions. :) if you just want to set fixed gas_limit or fee, you can set Fee in CreateTxOptions:
> 
> ```
>   tx_opt = CreateTxOptions(
>       msgs=[msg],
>       fee=Fee(200000, "12345uluna"),  # set gas_limit is 200000 and willing to pay 12345uluna as fee
>       # ...
>   )
> ```

**Comment by SheydaAshoorian** [comment]
@Vritra4  I mean is I just want to set fixed gas_limit . because when I set gas = auto don`t work. I should set fix gas. but I don`t know how to calculate gas in MsgMultiSend

**Comment by Vritra4** [comment]
@SheydaAshoorian just send some cases(diffferent in/out and count/amount) of MsgMultiSend to testnet. :)
Gas will be vary but not too much variation i guess. :)

**Comment by SheydaAshoorian** [comment]
> just send some cases(diffferent in/out and count/amount) of MsgMultiSend to testnet. :)
> Gas will be vary but not too much variation i guess. :)

I did the same , I wanted to see if terra offered an optimal solution. ;)

**Comment by SheydaAshoorian** [comment]
> @SheydaAshoorian just send some cases(diffferent in/out and count/amount) of MsgMultiSend to testnet. :) Gas will be vary but not too much variation i guess. :)

thank you
