### ISSUE TITLE
terra.tx.hash() throws AttributeError for any decoded transaction

### ISSUE THREAD

**Issue by DusanFedorcak** [terra-money/terra.py#108]
- terra_sdk version: 2.0.5 (built from source)
- Python version: 3.9
- Operating System: Ubuntu 20

### Description

`terra.tx.hash()` throws `AttributeError` for any transaction.
Workaround is possible by calling directly `terra_sdk.util.hash.hash_amino(b64_tx_data)`

### What I Did

```
from terra_sdk.client.lcd import LCDClient
from terra_sdk.util.hash import hash_amino
import base64
import time

terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")

bi = terra.tendermint.block_info(7223134)
tx = terra.tx.decode(bi["block"]["data"]["txs"][0])
terra.tx.hash(tx)
```
throws `AttributeError: 'MsgExecuteContract' object has no attribute 'pack_any'`

**Comment by DusanFedorcak** [comment]
I found another bug related to deserialization. Maybe it's also related to this one. 

```
from terra_sdk.client.lcd import LCDClient
from terra_sdk.util.hash import hash_amino

terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")

bi = terra.tendermint.block_info(7233659)
# this works
terra.tx.decode(bi["block"]["data"]["txs"][18])

# but this does not and crashes in TxBody.messages deserialization
terra.tx.tx_info(hash_amino(bi["block"]["data"]["txs"][18]))
```
error
```
File .../terra_sdk/core/authz/msgs.py:116, in MsgGrantAuthorization.from_data(cls, data)
    114 @classmethod
    115 def from_data(cls, data: dict) -> MsgGrantAuthorization:
--> 116     data = data["value"]
    117     return cls(
    118         granter=data["granter"],

KeyError: 'value'
```

**Comment by Aureliano90** [comment]
It's the same issue as [#100](https://github.com/terra-money/terra.py/issues/100). @Vritra4 should be working on decoding Msg.

**Comment by RICARDO4355** [comment]
> I found another bug related to deserialization. Maybe it's also related to this one.
> 
> ```
> from terra_sdk.client.lcd import LCDClient
> from terra_sdk.util.hash import hash_amino
> 
> terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")
> 
> bi = terra.tendermint.block_info(7233659)
> # this works
> terra.tx.decode(bi["block"]["data"]["txs"][18])
> 
> # but this does not and crashes in TxBody.messages deserialization
> terra.tx.tx_info(hash_amino(bi["block"]["data"]["txs"][18]))
> ```
> 
> error
> 
> ```
> File .../terra_sdk/core/authz/msgs.py:116, in MsgGrantAuthorization.from_data(cls, data)
>     114 @classmethod
>     115 def from_data(cls, data: dict) -> MsgGrantAuthorization:
> --> 116     data = data["value"]
>     117     return cls(
>     118         granter=data["granter"],
> 
> KeyError: 'value'
> ```

Hi @DusanFedorcak this is a mainnet related issue which is promting the bug causing the error. I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>> [TERRA DEVELOPERS LIVE CHAT](https://agora.terras.live/)  To help you sort this out right away
