### ISSUE TITLE
MsgWithdrawDelegatorReward.to_data() throws AttributeError

### ISSUE THREAD

**Issue by DusanFedorcak** [terra-money/terra.py#109]
- terra_sdk version: 2.0.5
- Python version: 3.9
- Operating System: Ubuntu 20

### Description

I'm sorry but there's another proto related error I guess. 
`MsgWithdrawDelegatorReward.to_data()` throws `AttributeError: 'MsgWithdrawDelegatorReward' object has no attribute 'withdraw_address'`

### What I Did

```
from terra_sdk.client.lcd import LCDClient
from terra_sdk.util.hash import hash_amino

bi = terra.tendermint.block_info(7235832)
bug_message = terra.tx.tx_info(hash_amino(bi["block"]["data"]["txs"][2])).tx.body.messages[0]
bug_message.to_data()
```
I'm scanning the block chain in real time for tx data so eventually I would face all tx types. The rest seems to be ok. I'll report if I found some more.

**Comment by DusanFedorcak** [comment]
I'm scanning the block chain in real time for tx data so eventually I would face all tx types. The rest seems to be ok. I'll report if I found some more.

**Comment by Vritra4** [comment]
thanks for the report. it will be released soon.
