### ISSUE TITLE
`TxInfo` created by `from_data` cannot be returned to data by `to_data`.

### ISSUE THREAD

**Issue by Aureliano90** [terra-money/terra.py#111]
- terra_sdk version: 2.0.5
- Python version: 3.10
- Operating System: Windows 10

### Description
`TxInfo` created by `from_data` cannot be returned to data by `to_data`.
```
res = terra.tx.tx_info('FB1A18E18078173DC90A80EB2843CD94DC3ACC1E61BAAD1CCDB92AA666FA14E3')
res.to_data()
```
### Error messages:
```
  File ".\public_key.py", line 154, in to_data
    return {"@type": self.type_url, "key": base64.b64encode(self.key)}
  File ".\base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'
```
### Cause:
`SimplePublicKey.key` is a `str` instead of `bytes`. `base64.b64encode` only takes `bytes`.

**Comment by RICARDO4355** [comment]
hi @Aureliano90 i just went through this, a bug seems to be prompting this error. I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the Forum ——>> [TERRA SUPPORT LIVE CHAT](https://agora.terras.live/)  to help you sort this out right away.
