### ISSUE TITLE
 rate limit for transaction

### ISSUE THREAD

**Issue by SheydaAshoorian** [terra-money/terra.py#114]
Is there rate limit for create transaction per minute or IP in mainnet?

**Comment by Aureliano90** [comment]
It shouldn't be. But there is a limit of 5 on number of connections to the LCD. I'm not sure how that is calculated. Would appreciate if @Vritra4 clarify on that.

Is it 5 requests on any API per second, or 5 APIs requested per second?

**Comment by Vritra4** [comment]
@SheydaAshoorian @Aureliano90 
yes there's a rate limit for public LCDs. 400 requests per 10seconds i guess. i'm not sure i'm not related with public LCDs.

**Comment by Aureliano90** [comment]
> @SheydaAshoorian @Aureliano90 yes there's a rate limit for public LCDs. 400 requests per 10seconds i guess. i'm not sure i'm not related with public LCDs. if you want more requests, you can run your own node and send requests to that.

Thanks. I often encounter this error.
```
Status 500 - max_subscriptions_per_client 5 reached
```
I don't think I ever reach 400 requests per 10 seconds. Also I'm not sure what is counted as one subscription. I only created one LCD instance.

**Comment by Vritra4** [comment]
@Aureliano90 oh that's the other problem. :)
400/10 is about load balancing for public nodes and max_subscription_per_client is from our (public) core node.
```
# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
```
