### ISSUE TITLE
 bombay-lcd.terra.dev:443 

### ISSUE THREAD

**Issue by SheydaAshoorian** [terra-money/terra.py#115]
Cannot connect to host bombay-lcd.terra.dev:443 ssl:default [nodename nor servname provided, or not known]: failed to get terra wallet balance!, Error"

when I disconnect psiphon get this error. is it need vpn for connecting?

**Comment by Vritra4** [comment]
no, vpn is not needed. check `https://bombay-lcd.terra.dev/swagger/` is reachable in your browser. if it is unreachable, it's your network problem i guess.

**Comment by steward833** [comment]
> Cannot connect to host bombay-lcd.terra.dev:443 ssl:default [nodename nor servname provided, or not known]: failed to get terra wallet balance!, Error"
> 
> when I disconnect psiphon get this error. is it need vpn for connecting?

Hello, A support ticket has been opened for you with Support ticket number TB7836SH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)
