### ISSUE TITLE
Problems using a wallet

### ISSUE THREAD

**Issue by NeoSephiroth** [terra-money/terra.py#116]
- terra_sdk version:  2.0.5
- Python version: 3.9
- Operating System: windows 11

### Description

I'm trying to do things using a wallet I created but everything I do gives me the error:  terra_sdk.exceptions.LCDResponseError: Status 404 - {'code': 5, 'message': 'rpc error: code = NotFound desc = account terra1k6crxnzym2cyrhf7mhn6q8vqe2a72a9f6tpdrn not found: key not found', 'details':

I am not new to cryptos. I have created various wallets and stored their private key and mnemonic correctly.
When trying to access them via google wallet extension these keys work.
When I try doing the same from python, it doesn't!

for instance this address here ( that has only testnet tokens) can be accessed using its mnemonic key via  chrome extension:

mnemonic: enforce spread gloom pull veteran erupt jungle absorb note transfer secret pull enroll brass lazy civil check stage remind chief latin cool group fiction

wallet: terra10eu5t9hrz8nhcpy4u9mydp52qcxp492nn74xvm

### 

```
from terra_sdk.client.lcd import LCDClient
from terra_sdk.key.raw import RawKey
from terra_sdk.key.mnemonic import MnemonicKey
from terra_sdk.core.bank import MsgSend
import requests
from terra_sdk.core.fee import Fee
from terra_sdk.client.lcd.api.tx import CreateTxOptions

MNEMONIC="enforce spread gloom pull veteran erupt jungle absorb note transfer secret pull enroll brass lazy civil check stage remind chief latin cool group fiction"

mk = MnemonicKey(MNEMONIC)
terra = LCDClient("https://lcd.terra.dev", "columbus-5")


wallet = terra.wallet(mk)



bluna_contract = 'terra1u0t35drzyy0mujj8rkdyzhe264uls4ug3wdp3x'



tx = wallet.create_and_sign_tx(CreateTxOptions(
        msgs=[MsgSend(
            wallet.key.acc_address,
            'terra1wu0x8ux6rc2mt06uvfcy56pwh7wkn6kvq0j5sk',
            "1000000uluna"    # send 1 luna
        )],
        memo="test transaction!",
        fee=Fee(200000, "120000uluna")
    ))

print(tx)

```

but this fragment of code gives me :

terra_sdk.exceptions.LCDResponseError: Status 404 - {'code': 5, 'message': 'rpc error: code = NotFound desc = account terra10eu5t9hrz8nhcpy4u9mydp52qcxp492nn74xvm not found: key not found', 'details':

**Comment by NeoSephiroth** [comment]
`import asyncio
from terra_sdk.client.lcd.api.tx import CreateTxOptions
from terra_sdk.client.lcd import AsyncLCDClient
from terra_sdk.key.mnemonic import MnemonicKey
from terra_sdk.core import Coins
from terra_sdk.core.bank import MsgSend

mk = MnemonicKey()
recipient = "terra10eu5t9hrz8nhcpy4u9mydp52qcxp492nn74xvm"

async def main():
    async with AsyncLCDClient("https://lcd.terra.dev", "columbus-5") as terra:
        wallet = terra.wallet(mk)
        account_number = await wallet.account_number()
        tx = await wallet.create_and_sign_tx(
            CreateTxOptions(
                msgs=[MsgSend(wallet.key.acc_address, recipient, Coins(uluna=10202))]
            )
        )

asyncio.get_event_loop().run_until_complete(main())`

**Comment by Aureliano90** [comment]
Your LCD is connected to the mainnet but your wallet has no fund on the mainnet. Transfer some funds or connect to the testnet.

**Comment by NeoSephiroth** [comment]
Thank you very much! 
I was Just realizing it by myself, too.
How do I have to change this ?
async with AsyncLCDClient("https://lcd.terra.dev", "columbus-5") as terra:

Columbus 5 is not right for testnet

**Comment by NeoSephiroth** [comment]
Finally everything seems to work!!

terra = LCDClient(chain_id="bombay-12", url="https://bombay-lcd.terra.dev/")

**Comment by Vritra4** [comment]
@NeoSephiroth feel free to reopen it if you still having a problem.
