### ISSUE TITLE
invalid Bech32 prefix; expected cosmos, got terra: invalid request

### ISSUE THREAD

**Issue by SheydaAshoorian** [terra-money/terra.py#131]
"Build transaction error. Status 400 - {'code': 3, 'message': 'invalid Bech32 prefix; expected cosmos, got terra: invalid request', 'details': []}: failed to create transaction !, Error",

**Comment by Vritra4** [comment]
It looks like you sent a tx with terra address to cosmos.

**Comment by Vritra4** [comment]
and like I mentioned in #126, i can't guarantee it works as you want. use their own sdk please.

**Comment by Aureliano90** [comment]
> It looks like you sent a tx with terra address to cosmos.

Can it be done via the `core.ibc` module? I don't see a demonstration.

**Comment by SheydaAshoorian** [comment]
@Vritra4 I want to transfer atom via terra sdk . because they are based on cosmos SDK

**Comment by Vritra4** [comment]
@SheydaAshoorian i don't know why do you want but keys from this sdk won't work because HRP is fixed to 'terra'.
