### ISSUE TITLE
How to get all transactions of a specific account?

### ISSUE THREAD

**Issue by Gitnnah** [terra-money/terra.py#139]
- terra_sdk version:
- Python version: 3.10.2
- Operating System: MacOS11

### Description

How do I get all transactions of a specific account?  

### What I Did

I started with...

```
from terra_sdk.client.lcd import LCDClient
terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")
transaktions=terra.tx.search([('message.sender','terra1...')])
```
### Error Message

terra_sdk.exceptions.LCDResponseError: Status 400 - {'code': 3, 'message': 'rpc error: code = InvalidArgument desc = must provide tx.height events for public node: invalid request', 'details': []}

Does someone have an idea how I can achieve this?

**Comment by Vritra4** [comment]
public lcd requires tx.height due to load balancing. you have to run your own node to skip this.

**Comment by Gitnnah** [comment]
Hm, and how do I do that? Do you have any material (articles, YT videos etc) to access this topic?

**Comment by Vritra4** [comment]
official docs to run a node: https://docs.terra.money/docs/full-node/run-a-full-terra-node/README.html
discord server: https://discord.com/invite/terra-money

**Comment by benfriedman** [comment]
Is there clear documentation anywhere on how to structure the search() events dictionary? I tried building a Python dict:

{"tx.height":7000000}

and passing that through but it didn't work. 

Additionally, is there any clear documentation on what the tx.height parameter means? Like, is it only finding transactions in exactly that block, or will it search for up to that block, or that block and after? I suspect it's only that block, but any confirmation would be much appreciated. Thanks very much.

**Comment by Vritra4** [comment]
https://github.com/terra-money/terra.py/blob/88b44ca2013ffdcab07b140824584d8b2be72ca7/tests/client/lcd/api/tx_test.py#L20
and yes, it's only for a block. you don't have to set tx.height for your own node. :)

**Comment by Gitnnah** [comment]
Thank you for the information.
