### ISSUE TITLE
Status 500 - timed out waiting for tx to be included in a block

### ISSUE THREAD

**Issue by cbarraford** [terra-money/terra.py#140]
- terra_sdk version: 2.0.4
- Python version: 3.9
- Operating System: mac

### Description

while doing a broadcast with block, i sometimes see this error
```
Status 500 - timed out waiting for tx to be included in a block
```

Is there a way to increase the timeout set by default?

**Comment by Vritra4** [comment]
the node you connected have timeout (10s by default) for broadcasted tx.
you can skip this timeout with broadcast_sync() but you'll have to query the tx you sent because broadcast_sync() returns before the tx have committed into a block.

**Comment by cbarraford** [comment]
is there a way to change the timeout from 10s to something larger?

**Comment by Vritra4** [comment]
if you are running a core node, you can update `rpc.timeout_broadcast_tx_commit` in config.toml.
else, you can use broadcast_sync() like i said.
