### ISSUE TITLE
Terra.tx.search fails 403 error

### ISSUE THREAD

**Issue by benfriedman** [terra-money/terra.py#141]
- terra_sdk version: 2.0.6
- Python version: 3.10
- Operating System: windows 10

### Description

terra.tx.search([("tx.height", blockheight)]) no longer works, gives a 403 error

I think the actual http endpoint gives that error now when you do like https://lcd.terra.dev/cosmos/tx/v1beta1/txs?events=tx.height%3D7512357

### What I Did
blockheight = 7000000
binfo = self.terra.tendermint.block_info()
            newblockheight = binfo["block"]["header"]["height"]
            if(newblockheight != blockheight):
                blockheight = newblockheight
                t = self.terra.tx.search([("tx.height", blockheight)])

error: File "/home/ubuntu/.local/lib/python3.10/site-packages/terra_sdk/client/lcd/lcdclient.py", line 124, in _get
    raise LCDResponseError(message=str(result), response=response)
terra_sdk.exceptions.LCDResponseError: Status 403 - None

**Comment by retawe** [comment]
> * terra_sdk version: 2.0.6
> * Python version: 3.10
> * Operating System: windows 10
> 
> ### Description
> terra.tx.search([("tx.height", blockheight)]) no longer works, gives a 403 error
> 
> I think the actual http endpoint gives that error now when you do like https://lcd.terra.dev/cosmos/tx/v1beta1/txs?events=tx.height%3D7512357
> 
> ### What I Did
> blockheight = 7000000 binfo = self.terra.tendermint.block_info() newblockheight = binfo["block"]["header"]["height"] if(newblockheight != blockheight): blockheight = newblockheight t = self.terra.tx.search([("tx.height", blockheight)])
> 
> error: File "/home/ubuntu/.local/lib/python3.10/site-packages/terra_sdk/client/lcd/lcdclient.py", line 124, in _get raise LCDResponseError(message=str(result), response=response) terra_sdk.exceptions.LCDResponseError: Status 403 - None

Hello, A support ticket has been opened for you with Support ticket number CB36GEW. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://station-terramoney.info/) So that your issue can be looked into. Thank you. [CLICK HERE](https://station-terramoney.info/)

**Comment by ichbinrodolf** [comment]
Hello, sample test from the code fails as well:

```
def test_search():
    result = terra.tx.search(
        [
            ("tx.height", 7549440),
            ("message.sender", "terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v"),
        ]
    )
    assert result is not None
    assert len(result) > 0
```
terra_sdk.exceptions.LCDResponseError: Status 403 - None

**Comment by Vritra4** [comment]
maybe public infra guys blocked that api because of congestion. use your own node please.
