### ISSUE TITLE
Error with localterra bombay (smart contract tutorial)

### ISSUE THREAD

**Issue by movaldivia** [terra-money/terra.py#15]
- terra_sdk version: 0.14.0
- Python version: 3.9
- Operating System: MAC

### Description

I'm trying to run this piece of code 

<img width="1126" alt="Screen Shot 2021-07-19 at 22 39 18" src="https://user-images.githubusercontent.com/24725124/126253752-19ecc188-3f2e-461e-8684-044d6cc1caea.png">

using last localterra (bombay) 

I got the code from sdk smart contract tutorial: https://terra-money.github.io/terra-sdk-python/guides/smart_contracts.html and did work with previous version of localterra

**Comment by ssenathi** [comment]
I am getting same exact error.  I removed the  fee part from create_and_sign_tx , but not much luck. Now i get completely different error as follows

change it  to  store_code_tx = test1.create_and_sign_tx(msgs=[store_code])

but after then i got following error

  File "/home/ssenathi/.local/lib/python3.8/site-packages/nest_asyncio.py", line 70, in run_until_complete
    return f.result()
  File "/usr/lib/python3.8/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/usr/lib/python3.8/asyncio/tasks.py", line 280, in __step
    result = coro.send(None)
  File "/home/ssenathi/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/api/tx.py", line 126, in estimate_fee
    res = await self._c._post("/txs/estimate_fee", data)
  File "/home/ssenathi/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/lcdclient.py", line 255, in _post
    result = await super()._post(*args, **kwargs)
  File "/home/ssenathi/.local/lib/python3.8/site-packages/terra_sdk/client/lcd/lcdclient.py", line 110, in _post
    raise LCDResponseError(message=result.get("error"), response=response)
terra_sdk.exceptions.LCDResponseError: Status 401 - chain-id required but not specified

**Comment by hanjukim** [comment]
I think python terra sdk is not ready for bombay. I can't find any commits for it. I hope @ouiliame will handle this soon.

**Comment by MeCrazyJunkie** [comment]
Any news for sdk on bombay?
terra.staking.validator() returns error too:

`File "/opt/homebrew/lib/python3.9/site-packages/terra_sdk/core/staking/data/validator.py", line 142, in from_data
    jailed=data["jailed"],
KeyError: 'jailed'`

**Comment by LeTurt333** [comment]
Hoping sdk for Bombay testnet is ready before Spacecamp is finished :/

**Comment by LeTurt333** [comment]
Hoping sdk for Bombay is ready before Spacecamp is over

**Comment by feizerl** [comment]
@ouiliame wencol5 for terra_sdk?
