### ISSUE TITLE
await is missing on contract_info

### ISSUE THREAD

**Issue by GiacomoEncicliati** [terra-money/terra.py#151]
- terra_sdk version: 3.0.0
in clinet/lcd/api/wasm.py, row 60

`history_entries = self.contract_history(contract_address)`

`contract_history` is a coroutine, and need to be `await`

`history_entries = await self.contract_history(contract_address)`

**Comment by JSHan94** [comment]
thanks for contribution. Closed #152

**Comment by JSHan94** [comment]
To review it, i found that `contract_history()` returns list, not async func. So `await` keyword is not needed. It already awaits requests inside of  `contract_history()`. Actually, if we add `await` like you said, it will make an error.
#158 PR will be reverted.

**Comment by JSHan94** [comment]
Closes #159
