### ISSUE TITLE
wrong call for account_number and sequence

### ISSUE THREAD

**Issue by GiacomoEncicliati** [terra-money/terra.py#153]
- terra_sdk version: 3.0.0

in client/lcd/wallet, line 27:
`return {"account_number": res.account_number, "sequence": res.sequence}`

In case that `res` is not a `BaseAccount`,  `res.account_number` and `res.sequence` variables are not present.
They should be called via method `get_account_number()` and `get_sequence()`

The modification should be:

`return {"account_number": res.get_account_number(), "sequence": res.get_sequence()}`

I think this problem could be present in other part of library

**Comment by JSHan94** [comment]
@GiacomoEncicliati  Thanks for your contribution. Could you make a PR for this?

**Comment by JSHan94** [comment]
Closes #159
