### ISSUE TITLE
Add Terra Classic support

### ISSUE THREAD

**Issue by Polsaker** [terra-money/terra.py#154]
- terra_sdk version: 3.0.0
- Python version: 3.10
- Operating System: Linux

### Description

I want to use both Terra Classic **and** Terra 2.0 with the same library version

**Comment by JSHan94** [comment]
We don't have plan yet to support classic terra with trera-sdk 3.x. If there's any update, we will annonce it. Like #150, you can use terra-sdk 2.0.6 for classic.
