### ISSUE TITLE
AttributeError: 'str' object has no attribute 'denom'

### ISSUE THREAD

**Issue by CoinInn-Aries** [terra-money/terra.py#167]
- terra_sdk version: 2.0.6
- Python version: 3.8.2
- Operating System: Macos

### Description
Is it my parameter?
`from jigu.key.mnemonic import MnemonicKey
from terra_sdk.core.fee import Fee
from jigu.core.msg import MsgSend
from terra_sdk.client.lcd.api.tx import CreateTxOptions
from terra_sdk.client.lcd import LCDClient

terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev/")

wallet = terra.wallet(MnemonicKey.generate())
print(wallet.key.acc_address)

tx = wallet.create_and_sign_tx(CreateTxOptions(
msgs=[MsgSend(
wallet.key.acc_address,
wallet.key.acc_address,
"1000000uluna" # send 1 luna
)],
memo="test transaction!",
fee=Fee(200000, "120000uluna")
))`

### What I Did

```

Traceback (most recent call last):
  File "/Users/aries/work/github/terra/terra-chain/terra-classic/TerraClassic.py", line 13, in <module>
    msgs=[MsgSend(
  File "<string>", line 6, in __init__
  File "/Users/aries/work/github/twitter/twint/venv/lib/python3.8/site-packages/jigu/core/msg/bank.py", line 37, in __post_init__
    self.amount = Coins(self.amount)
  File "/Users/aries/work/github/twitter/twint/venv/lib/python3.8/site-packages/jigu/core/sdk/coin.py", line 178, in __init__
    if self._cd.get(coin.denom, None) is None:
AttributeError: 'str' object has no attribute 'denom'

```

**Comment by Vritra4** [comment]
use Coins instead of str for Fee.
like `fee=Fee(200000, Coins(uluna=120000))`

**Comment by CoinInn-Aries** [comment]
> 

from jigu.key.mnemonic import MnemonicKey
from terra_sdk.core.fee import Fee
from jigu.core import Coins
from jigu.core.msg import MsgSend
from terra_sdk.client.lcd.api.tx import CreateTxOptions
from terra_sdk.client.lcd import LCDClient

terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")

wallet = terra.wallet(MnemonicKey.generate())
print(wallet.key.acc_address)

tx = wallet.create_and_sign_tx(CreateTxOptions(
    msgs=[MsgSend(
        wallet.key.acc_address,
        wallet.key.acc_address,
        "1000000uluna"  # send 1 luna
    )],
    memo="test transaction!",
    fee=Fee(200000, Coins(uluna=120000))
))
Tips are still the same

**Comment by CoinInn-Aries** [comment]
>
