### ISSUE TITLE
Dec cannot represent a value smaller than 1e-6

### ISSUE THREAD

**Issue by Matthew-Jennings** [terra-money/terra.py#17]
- terra_sdk version: 0.14.0
- Python version: 3.9.5
- Operating System: Windows 10 Pro (build 19043.1110)

### Description

Hi there,

I've started to put together [my own little python API](https://github.com/Matthew-Jennings/anchorpy) for [Anchor Protocol](https://github.com/Anchor-Protocol), and I'm trying to multiply a `Dec` coin by ~`4e-8`. Specifically, I'd like to increment the value of a `Coin` object with `denom="uaust"` by Anchor Earn's per-block deposit rate. It would be convenient to use `Coin`'s `mul()` function for this, since I'd like to return a new `Coin` object.

Unfortunately, I've just discovered that the smallest value that `Dec` can (accurately) represent is `1e-6` - much higher than I need! See minimal demo below.

Is this by design / expected? Perhaps related to the convention of working in micro currency units?

If this behaviour is expected and difficult/unlikely to change, may I humbly suggest a rewording of the `Dec` class docstring? Perhaps it could explicitly state this minimum? Also, at the moment, the docstring states that `Dec` (my emphasis):

> [...]Serializes as a string with 18 points of **decimal** precision.

which I found a little confusing. To me at least, "18 points of decimal precision" implies that 1e-18 (or thereabouts) can be represented.

I'd be happy to work on any agreed-upon changes and submit a pull request :)

[EDIT]

I just discovered that constructing with a decimal string works fine! Not with a scientific notation string though. See second code block below.

### What I Did

```bash
$ python
>>> from terra_sdk.core import Dec
>>> print(Dec(5e-7))
0.000000000000000000
>>> print(Dec(5e-7 + 1e-20))
0.000001000000000000
>>> print(Dec(5e-7 + 1e-20) == Dec(1e-6))
True
```

[EDIT] Decimal string okay:
```bash
$ python
>>> from terra_sdk.core import Dec
>>> print(Dec(0.000000005))
0.000000000000000000
>>> print(Dec("0.000000005"))
0.000000005000000000
>>> print(Dec(5e-9))
0.000000000000000000
>>> print(Dec("5e-9"))
.....
ValueError: Unable to parse Dec from string: 5e-9
```

**Comment by Matthew-Jennings** [comment]
Just to add a little more info: constructing with a decimal string works fine! Not with a scientific notation string though.

```bash
$ python
>>> from terra_sdk.core import Dec
>>> print(Dec(0.000000005))
0.000000000000000000
>>> print(Dec("0.000000005"))
0.000000005000000000
>>> print(Dec(5e-9))
0.000000000000000000
>>> print(Dec("5e-9"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\core\numeric.py", line 92, in __init__
    self._i = int(convert_to_dec_bignum(arg))
  File "C:\Users\Matthew\AppData\Local\Programs\Python\Python39\lib\site-packages\terra_sdk\core\numeric.py", line 28, in convert_to_dec_bignum
    raise ValueError(f"Unable to parse Dec from string: {arg}")
ValueError: Unable to parse Dec from string: 5e-9
```

**Comment by ouiliame** [comment]
`Dec` is not confirmed to work nicely with native `float` types -- it supports direct conversion but there are a bunch of kinks with precision. We recommend using the decimal string.

fyi. `Dec` is a fixed-point implementation of decimals
