### ISSUE TITLE
Not working for Bombay-10

### ISSUE THREAD

**Issue by sunny334** [terra-money/terra.py#19]
- terra_sdk version: latest
- Python version: 3.7
- Operating System: Linux

### Description

I am trying to fetch the total supply to test the API.
Working fine for tequila-0004.
When I change testnet to Bombay-10 it give me 501.

### What I Did

```

import asyncio 
from terra_sdk.client.lcd import AsyncLCDClient

async def main():

	terra = AsyncLCDClient("https://bombay-lcd.terra.dev","bombay-9")
	total_supply = await terra.supply.total()
	print(total_supply)
	#await terra.session.close # you must close the session

asyncio.get_event_loop().run_until_complete(main())


```

**Comment by sunny334** [comment]
@hanjukim

**Comment by Vritra4** [comment]
supply.total() has moved bank.total() for 1.0
