### ISSUE TITLE
Request Support for BLS12 based signature verification

### ISSUE THREAD

**Issue by sudesh-supraoracles** [terra-money/terra.py#26]
Hi Team!

Since many protocols are putting BLS12 to use for digital signatures.
I want to verify BLS 12 based signature from Terra smart contract.

Hoping for some positive inputs/response on this.

**Comment by Vritra4** [comment]
sorry for the late response. unfortunately BLS12 is not supported yet. maybe it will be supported when cosmwasm 1.2+.
