### ISSUE TITLE
Equivalent for v1 txs API

### ISSUE THREAD

**Issue by Retsim** [terra-money/terra.py#29]
- terra_sdk version: Latest columbus-5
- Python version: 3.7
- Operating System: Unix (google Collaboratory experiments)

### Description

The V1 txs API endpoint allows to search for transactions using account ID, ex:
https://fcd.terra.dev/v1/txs?limit=100&account=terra1hyxq9usxp7fge5lx7qx3k0mqe2u55fv4xptqtc

The non-v1 API seems deprecated:
https://fcd.terra.dev/swagger

Terra-SDK looks to use the same params as the deprecated API for it's txs searches, we can call:
`transactions = terra.tx.search({"message.sender":wallet})`

But we cannot call:
`transactions = terra.tx.search({"account":wallet})`

Is there a way or to do this ?
Documentation is unclear about this method options.

Thanks !

**Comment by kostistsaprailis** [comment]
Any update?

**Comment by kostistsaprailis** [comment]
So I have been digging into this, is think the python-sdk is using only using the old deprecated non-v1 API.

Checking here the search function:
[async def search(self, options: dict = {}) -> dict:](https://github.com/terra-money/terra.py/blob/29e4ccd3a2848405a923891e30eb61a5930d14f1/terra_sdk/client/lcd/api/tx.py#L238)
you can see it's using the old API:
https://github.com/terra-money/terra.py/blob/29e4ccd3a2848405a923891e30eb61a5930d14f1/terra_sdk/client/lcd/api/tx.py#L247

I don't think there's a way to use the new v1 API via the sdk. What I will do is just use the public [URL](https://fcd.terra.dev/v1/txs?) to perform the request, manually until the SDK is updated.

**Comment by Vritra4** [comment]
new version is out now. :) 
query like this:
```
   terra = LCDClient(...)
   result = terra.tx.search([
          ("tx.height", 7549440),
          ("message.sender", "terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v"),
      ])
      print("tx_search", result)
```
tx.height is mandatory for public nodes.
