### ISSUE TITLE
Can't get tx_info for hash from columbus-4

### ISSUE THREAD

**Issue by pharr117** [terra-money/terra.py#40]
- terra_sdk version: 1.0.0
- Python version: 3.9.7
- Operating System: Ubuntu 18.04.6 LTS

### Description

In release 1.0.0, I cannot seem to get transaction info by tx hash when the network is columbus-4. I believe it is not respecting the chain_id value when creating the LCDClient object,

### What I Did

I created a columbus-4 chain_id LCDClient object. 

I followed the example in the docs [here](https://terra-money.github.io/terra.py/guides/lcdclient.html#get-connected) to output the tendermint.node_info network, and it returns "columbus-5" instead of "columbus-4".

I then tried to get tx_info for a transaction. The transaction definitely exists because I can find it in Terra Finder no problem. However, the request returns a 404.
```
from terra_sdk.client.lcd import LCDClient
terra = LCDClient(url="https://lcd.terra.dev", chain_id="columbus-4")
terra.tendermint.node_info()['node_info']['network']
>>> 'columbus-5'

terra.tx.tx_info(<tx hash>) 
>>> terra_sdk.exceptions.LCDResponseError: Status 404 - tx (<tx hash>) not found
```

**Comment by dankorob** [comment]
Hi @pharr117,
Let me try to answer you.
1. Terra network was officially upgraded from Columbus-4 to Columbus-5: https://station.terra.money/proposal/119. Thus, Columbus-4 is no more a valid version of the network to run.
2. After connecting to the Terraform Labs public node (`https://lcd.terra.dev`), it gets info from the node and as it runs on the latest network version you can see `columbus-5` as the output. The `chain_id` is an `Optional` field in `LCDClient` so it was just ignored.
3. The Python-SDK `main` is still not ready for Col-5. But you can use the `1.0.0b3` terra.py version with coming changes for Col-5: #20.
4. Your code actually works fine:
```
terra = LCDClient(url="https://lcd.terra.dev", chain_id="columbus-5")
network_info = terra.tendermint.node_info()['node_info']['network']
tx_info = terra.tx.tx_info('C0CA590A324FDCC9A289152C2C12F38D306FFE2BFC67C83721E968B811E6D350')
print(tx_info)
```
Output:
```
TxInfo(height=5120726, txhash='C0CA590A324FDCC9A289152C2C12F38D306FFE2BFC67C83721E968B811E6D350', rawlog='[{"events":[{"type":"execute_contract","attributes":[{"key":"sender","value":"terra1.......}]....')
```

**Comment by hanjukim** [comment]
One thing to add is that the `main` branch is compatible with columbus-5 and #20 PR has been closed.

**Comment by Vritra4** [comment]
`columbus-5` branch is compatible with columbus-5 actually. it will be merged into main soon with new endpoints.

**Comment by hanjukim** [comment]
Steps you want to search transactions in previous network:

1. Get a snapshot for the network from https://quicksync.io/networks/terra.html
2. Find proper tag of Terra Core (The latest one for Columbus-4 is `v0.4.6`) and compile a executable binary
3. Get the genesis of network from https://github.com/terra-project/mainnet
4. Setup terrad and start
5. Setup LCD (i.e. terracli rest-server --trust-node --laddr 0.0.0.0:1317)
5. Assign http://<above host address>:1317 as `url`

**Comment by dankorob** [comment]
https://github.com/terra-money/terra.py/issues/40#issuecomment-955851469
