### ISSUE TITLE
How to set slippage maximum for sell swap

### ISSUE THREAD

**Issue by thinkdandscript** [terra-money/terra.py#43]
- terra_sdk version: 1.0.0
- Python version: 3.10
- Operating System: Windows 11

### Description

I'm trying to put in a slippage maximum when selling a contract token (e.g. LOOP) for UST. I know how to do this on the buy side but haven't been able to figure out how to do so when selling.  Can anyone point me to documentation that talks about this?

### What I Did

```
I have tried doing a transaction manually through terraswap and using a slippage maximum, looking at the popup box to check the execute message and how it's set up, but still I don't see anything that changes when setting different slippage parameters.
```

**Comment by Vritra4** [comment]
sdk has no relation with slippage. maybe slippage tolerance would be set in execute_msg in MsgExecuteContract.
