### ISSUE TITLE
Can't get block info for block height below 4724001

### ISSUE THREAD

**Issue by oun** [terra-money/terra.py#44]
- terra_sdk version: 1.0.0
- Python version: 3.7.10
- Operating System: OSX

### Description

I can't get block info for block height below 4724001 even specify chain ID columbus-4.
How can I get all block info  for those blocks?

### What I Did

```
terra = LCDClient(chain_id="columbus-4", url="https://lcd.terra.dev")
pprint(terra.tendermint.block_info(1))
```

it raise error:

```
terra_sdk.exceptions.LCDResponseError: Status 500 - height 1 is not available, lowest height is 4724001
```

**Comment by Vritra4** [comment]
like the error mentioned, lowest height of columbus-5 is 4724001, not 1.
you can't get block info for columbus-4 with LCD.
