### ISSUE TITLE
Error Estimating TX Fee

### ISSUE THREAD

**Issue by Michael-C-Dev** [terra-money/terra.py#46]
- terra_sdk version: 1.01
- Python version: 3.9
- Operating System: Windows 10

### Description

I am attempting to use the `terra.tx.estimate_fee()` to provide an estimate of the fee cost for submitting a transaction which requires a the Union of a `StdSignMsg` and a `StdTx`. `StdSignMsg` requires a `fee` parameter which seems to defeat the purpose of estimating the fee. If you continue along and provide the fee, `tx.estimate_fee()` requires the Union of two nonhashable objects to form a `tx` object? I am looking to get a value similar to how Terra Station estimates the fee cost for a transaction. Is this the correct function or should I be looking at something else?

### What I Did

```
try:
    terra = LCDClient(chain_id="bombay-12", url="https://bombay-lcd.terra.dev")
    mk = MnemonicKey(mnemonic="<mnumonic>")
    wallet = terra.wallet(mk)
    tx = wallet.create_and_sign_tx(
        msgs=[MsgSend(wallet.key.acc_address,
                      "terra1fa0trn2nqjc2n6mmz9txta7ky5h5nnp9m6cra3", "1000uluna")],
        memo="test transaction!",
        fee_denoms=["uluna"])
    stdmsg = StdSignMsg(chain_id="bombay-12", account_number=wallet.account_number(), sequence=wallet.sequence(), msgs=[MsgSend(wallet.key.acc_address,
                      "terra1y0acvg6lsla7hugagm2scapqqx5fp59gukptmv", "1000uluna")], memo="Test", fee="20000uluna")
    print(terra.tx.estimate_fee({stdmsg, tx}))
    print(tx)
except LCDResponseError as e:
    print(e)
```

The Error: 
```
Traceback (most recent call last):
  File "C:/Users/User/git_repos/terra/main.py", line 36, in estimate_fee_bombay
    print(terra.tx.estimate_fee({stdmsg, tx}))
TypeError: unhashable type: 'StdSignMsg'
```

**Comment by Vritra4** [comment]
thanks for reporting. it'll be fixed.
you can ignore estimate_fee definition and can do like it because the definition is just a stub.
`print(terra.tx.estimate_fee(sender=wallet.key.acc_address,msgs=tx.msg))`

**Comment by Michael-C-Dev** [comment]
Thank you @Vritra4 for the quick response! I swapped the estimate fee using the parameters you specified (e.g. `print(terra.tx.estimate_fee(sender=wallet.key.acc_address,msgs=tx.msg))`); however, it returns an empty `Coins()` object rather than a list of denominations as shown in the print output: `StdFee(gas=52331, amount=Coins())`. I removed the `fee_denoms=["uluna"]` parameter as well which did not change the result.

I confirmed that I am using terra-sdk 1.0.2 as output from `pip list`: `terra-sdk          1.0.2`. Please let me know if I misunderstood your message or if the issue has yet to be resolved

**Comment by Vritra4** [comment]
@Michael-C-Dev oh gas prices are unspecified :)
you can set gas_prices, gas_adjustment and fee_denoms when you call estimate_fee().

`print(terra.tx.estimate_fee(sender=wallet.key.acc_address, msgs=tx.msg, gas_prices="0.015uusd"))`
-> `StdFee(gas=52456, amount=Coins('787uusd'))`
or
`print(terra.tx.estimate_fee(sender=wallet.key.acc_address, msgs=tx.msg, gas_prices="0.15uusd,0.015uluna", fee_denoms="uluna"))`
->  `StdFee(gas=52466, amount=Coins('787uluna'))`
