### ISSUE TITLE
Update ecdsa to 0.17.0

### ISSUE THREAD

**Issue by Polsaker** [terra-money/terra.py#51]
- terra_sdk version: 1.0.2
- Python version: 3.10
- Operating System: MacOS/Linux

### Description

Can you please update ecdsa to 0.17.0 or relax the pinning? This library currently has it pinned on `ecdsa<0.17.0 and >=0.16.1`, which is now in conflict with a bunch of other libraries.

### What I Did

Try `pip install terra-sdk==1.0.2 substrate-interface==1.1.4` and watch the fireworks

**Comment by Vritra4** [comment]
okay i'll do that after checking sideeffects. :)
