### ISSUE TITLE
Fetching proposal_id error due key error.

### ISSUE THREAD

**Issue by unl1k3ly** [terra-money/terra.py#57]
### Description

Fetching a `proposal_id` using `terra.gov.proposal()` does not work because there is an error in the object that looks for `proposal_status` where it should be `status` instead.

https://github.com/terra-money/terra.py/blob/e6528d268476841f0f4d77834116347bf7fb3de8/terra_sdk/core/gov/data.py#L77

Data sample:

```
{'id': '175', 'content': {'type': 'distribution/CommunityPoolSpendProposal', 'value': {'title': 'UST Goes Interchain: Degen Strats Part Four', 'description': 'Bring UST to Market.xyz and Themis\nhttps://agora.terra.money/t/ust-goes-interchain-degen-strats-part-four/3599', 'recipient': 'terra1jrhxdtwxrsxw3t2al6t3sga89974juhpccuxct', 'amount': [{'denom': 'uusd', 'amount': '40000000000000'}]}}, 'status': 2, 'final_tally_result': {'yes': '0', 'abstain': '0', 'no': '0', 'no_with_veto': '0'}, 'submit_time': '2022-01-11T19:11:20.807833336Z', 'deposit_end_time': '2022-01-25T19:11:20.807833336Z', 'total_deposit': [{'denom': 'uluna', 'amount': '50000001'}], 'voting_start_time': '2022-01-12T01:26:01.593909182Z', 'voting_end_time': '2022-01-19T01:26:01.593909182Z'}
```

I'd do a PR but I'm not sure how you wanted to handle this as I believe proto files would need to be updated also ...

Thanks

**Comment by Vritra4** [comment]
sorry for your inconvenience. it will be fixed with v2.

**Comment by Vritra4** [comment]
v2.0.0 released
