### ISSUE TITLE
Fetch market price of mAssets

### ISSUE THREAD

**Issue by YilmazKadir** [terra-money/terra.py#66]
Hi, I am new to Terra SDK python and wanted to learn how I can fetch market price of non-native Terra tokens such as mAssets from the SDK. I would be very happy if you could guide me as I could not find much information about non-native assets.

**Comment by Vritra4** [comment]
you can query cw20 tokens with LCDCLient.wasm.contract_query.

```
terra = LCDClient(...)
result = terra.wasm.contract_query(
  mAsset_address,
   {"balance": {"address": account_address}},
)
print(result)
```
