### ISSUE TITLE
`estimate_fee()` rounds calculated fee amount down instead of up

### ISSUE THREAD

**Issue by zhongfu** [terra-money/terra.py#70]
`estimate_fee()` rounds the calculated fee amount down instead of up, so using the calculated estimate directly often causes transactions to be rejected by LCDs with a minimum gas price set:

```
insufficient fees; got: "261368uusd", required: "331067uaud,331067ucad,243944uchf,1707605ucny,1568209udkk,217807ueur,191670ugbp,2038672uhkd,3798549720uidr,18957900uinr,28523972ujpy,295816416ukrw,19743uluna,746765254umnt,2178068unok,13242651uphp,182850usdr,2178068usek,348491usgd,8050138uthb,261369uusd" = "331067uaud,331067ucad,243944uchf,1707605ucny,1568209udkk,217807ueur,191670ugbp,2038672uhkd,3798549720uidr,18957900uinr,28523972ujpy,295816416ukrw,19743uluna,746765254umnt,2178068unok,13242651uphp,182850usdr,2178068usek,348491usgd,8050138uthb,261369uusd"(gas) +""(stability): insufficient fee
```

This is for a tx with a gas limit of 1742454, which would require a minimum fee of `0.15uusd * 1742454 = 261368.1uusd ~= 261369uusd` on the public Bombay LCD.

`estimate_fee()` rounds the calculated fee down with `to_int_coins()` though, so the calculated fee amount is `261368` instead (i.e. gas price is `0.149999943uusd` -- below the min price of `0.15uusd`)

https://github.com/terra-money/terra.py/blob/97b84f5ba772ed75abd0bbcb84b4b525a99c5346/terra_sdk/client/lcd/api/tx.py#L222

**Comment by luigi311** [comment]
I am also getting the same result when testing the new changes on bombay-12. Getting the same error message
```
Error: insufficient fees; got: "77993uusd", required: "98792uaud,98792ucad,72794uchf,509558ucny,467962udkk,64995ueur,57196ugbp,608350uhkd,1133506260uidr,5657133uinr,8511697ujpy,88273100ukrw,5892uluna,222838492umnt,649947unok,3951674uphp,54564usdr,649947usek,103992usgd,2402202uthb,77994uusd" = "98792uaud,98792ucad,72794uchf,509558ucny,467962udkk,64995ueur,57196ugbp,608350uhkd,1133506260uidr,5657133uinr,8511697ujpy,88273100ukrw,5892uluna,222838492umnt,649947unok,3951674uphp,54564usdr,649947usek,103992usgd,2402202uthb,77994uusd"(gas) +""(stability): insufficient fee
```
Tried to use the gas_adjustment  but that just increases the fees but also keeps the round down by 1 so it still fails with the same message.

**Comment by luigi311** [comment]
Can confirm this is resolved
