### ISSUE TITLE
is_tx_error() fails due to code now being 0 instead of None

### ISSUE THREAD

**Issue by luigi311** [terra-money/terra.py#72]
- terra_sdk version: 2.0.3
- Python version: 3.10
- Operating System: Windows 10

### Description
Doing a broadcast now returns result.code = 0 instead of result.code = None so now is_tx_error(result) fails

### What I Did

```
sendtx = self.wallet.create_and_sign_tx(CreateTxOptions(
    msgs=[execute],
    fee_denoms=["uusd"],
))
result = self.terra.tx.broadcast(sendtx)

error = is_tx_error(result)
if error:
    raise Exception(
        f"Transaction failed, TX_ID: {result.txhash}\nError: {result.raw_log}"
    )
```
this always triggers because is_tx_error always returns true now.

2.0.3
result: ......., code=0, codespace='', info=None, data=None, timestamp=None)

1.0.2
result: ........, code=None, codespace=None)

**Comment by luigi311** [comment]
I fixed this locally just by changing is_tx_error to check for 0 instead of None but i dont think thats the solution you guys want, i wasnt sure where the 0 was coming from instead of None and figured it would be faster for you guys to check and decide what you guys want.

**Comment by Vritra4** [comment]
thank you for reporting! i think just 0 is fine. new version will be released after adding more fixs and features.
