### ISSUE TITLE
Failed StdFee Import

### ISSUE THREAD

**Issue by naviator99** [terra-money/terra.py#74]
- terra_sdk version: 2.0.3
- Python version: 3.7
- Operating System: Windows 10 64-bit

Hi everyone,

I'm trying to do the simple tutorials, which can be found in the Terra SDK Documentation.
All imports work fine, but not the StdFee import. 
Am I doing something wrong or is there an other way to implement fees?

I used the exact same implementation as in the documentation.
https://terra-money.github.io/terra.py/guides/transactions.html?highlight=fees
https://terra-money.github.io/terra.py/core_modules/auth.html?highlight=fees

![image](https://user-images.githubusercontent.com/100239641/155220720-a5ef0dee-eced-41dc-847a-825f11a68f2e.png)

**Comment by Vritra4** [comment]
sorry docs are being updated.. you can use Fee instead of StdFee.

```
from terra_sdk.client.lcd import LCDClient
from terra_sdk.client.lcd.api.tx import CreateTxOptions
from terra_sdk.core import Coins
from terra_sdk.core.bank import MsgSend
from terra_sdk.core.fee import Fee
from terra_sdk.key.mnemonic import MnemonicKey

terra = LCDClient(
        url="https://bombay-lcd.terra.dev/",
        chain_id="bombay-12",
        )

mk = MnemonicKey(
        "notice oak worry limit wrap speak medal online prefer cluster roof addict wrist behave treat actual wasp year salad speed social layer crew genius"
        )

test1 = terra.wallet(mk)

msg = MsgSend(
        "terra1x46rqay4d3cssq8gxxvqz8xt6nwlz4td20k38v",
        "terra17lmam6zguazs5q5u6z5mmx76uj63gldnse2pdp",
        Coins(uluna=1000000),
        )

tx = test1.create_and_sign_tx(CreateTxOptions(
    msgs=[msg], fee=Fee(200000, Coins.from_str("30000uusd"))
    ))

result = terra.tx.broadcast(tx)
print(result)
```

**Comment by Vritra4** [comment]
still updating but recently deployed docs are more useful i guess.
