### ISSUE TITLE
create_and_sign_tx Error - 'str' object has no attribute 'sequence'

### ISSUE THREAD

**Issue by alienHunterOnMars** [terra-money/terra.py#79]
- terra_sdk version: 2.0.3

### Description

I am getting error `'str' object has no attribute 'sequence'` with the `create_and_sign_tx` function with the latest stable release version. 

I am using the `CreateTxOptions` as mentioned in other issues, but am getting this ^ error now. 

```
execute_msg = MsgExecuteContract(wallet.key.acc_address, contract_addr , msg_struct )
tx_opt = CreateTxOptions(msgs=[execute_msg], fee_denoms=['uusd'], memo=".")
tx = await wallet.create_and_sign_tx( tx_opt )
res = await self.terra.tx.broadcast(tx)
```

Can you please help me get this working. ?

**Comment by Vritra4** [comment]
@alienHunterOnMars how did you create wallet?

**Comment by alienHunterOnMars** [comment]
mk = MnemonicKey(mnemonic= mnenonic )
wallet = self.terra.wallet(mk)

looks okay, as `print(wallet.key.acc_address)` gives me the wallet address

**Comment by alienHunterOnMars** [comment]
note that i am using an `AsyncWallet` here

**Comment by alienHunterOnMars** [comment]
@Vritra4 i think the error is occuring here - https://github.com/terra-money/terra.py/blob/ccf72f8e7c66f1442b3b5a691f5da7e1aeafbc70/terra_sdk/client/lcd/wallet.py#L29

as we are passing the wallet address string to the `create` function (https://github.com/terra-money/terra.py/blob/ccf72f8e7c66f1442b3b5a691f5da7e1aeafbc70/terra_sdk/client/lcd/api/tx.py#L142) which accepts a list of `SignerOptions` instead, using which it gets the `sequence`. 

Here it gives error for `AsyncWallet` instances as we are just passing the wallet address as string ? Makes sense ?

**Comment by Vritra4** [comment]
yeah makes sense.. i'll release fixed version soon. thanks!

**Comment by alienHunterOnMars** [comment]
Looks like the whole `AsyncWallet` functions are incomplete and untested.

- when calling `sign_tx` (https://github.com/terra-money/terra.py/blob/ccf72f8e7c66f1442b3b5a691f5da7e1aeafbc70/terra_sdk/client/lcd/wallet.py#L34) `options` are not being passed which are being passed here - https://github.com/terra-money/terra.py/blob/ccf72f8e7c66f1442b3b5a691f5da7e1aeafbc70/terra_sdk/client/lcd/wallet.py#L104

- `estimate_gas` async function is not awaited here -  https://github.com/terra-money/terra.py/blob/ccf72f8e7c66f1442b3b5a691f5da7e1aeafbc70/terra_sdk/client/lcd/api/tx.py#L219

Looks like i will have to revert to 1.0.2 version for now. Please don't make it a stable release when its not complete, took me 2 days to figure that issues are with the SDK version here.

**Comment by samueldgSBCS** [comment]
Many other issues with async version. 
In general many methods are not awaited (posted another issues on Broadcast problems). 
-> some static methods are defined as asyncronous for no reasons
-> Some asyncronously-defined methods are not awaited

I suggest revising the whole asynchronous. 
I also suggest switching development to full async (no syncronous files) as the immense majority of serious applications for this library require async integration & it will narrow down failure points. 

Thank you for the efforts ! Really appreciate the content though, you really make a great job for this service !

**Comment by Vritra4** [comment]
@samueldgSBCS @alienHunterOnMars sorry for your inconvenience. v2.0.4 released.
