### ISSUE TITLE
terra 2.0.3 typo / bug in asyncronous broadcast method

### ISSUE THREAD

**Issue by samueldgSBCS** [terra-money/terra.py#80]
- terra_sdk version: 2.0.3
- Python version: 3.9
- Operating System: Not relevant

### Description

in :
> terra_sdk/client/lcd/api/tx.py
> method _broadcast (line 247)
data = {"tx_bytes": self.encode(tx), "mode": mode}
self.encode (l227) is defined as an asyncronous method and is never awaited, thus failing the Json serialisation. 

-> self.encode should not be defined as asyncronous (it does not perform asyncronous operations). 
-> self.decode (l231) neither, it may cause another failure later in the execution.

Please patch those issues before using terra 2.0.3 as a deployed service, it may open up unforeseen vulnerabilities.

### What I Did

await terra.tx.broadcast(signed_tx)

**Comment by Vritra4** [comment]
thank you for reporting us.
you can test https://github.com/terra-money/terra.py/blob/main/integration_tests/async_codec.py with v2.0.4.
