### ISSUE TITLE
terra_sdk.exceptions.LCDResponseError: Status 404 'key not found'

### ISSUE THREAD

**Issue by RylandCapital** [terra-money/terra.py#82]
- terra_sdk version: 2.0.3
- Python version: 3.9.4
- Operating System: Windows

### Description
just following example. I put in my mnemonic and run. 

![image](https://user-images.githubusercontent.com/16804873/157309487-bcdf8dba-4f62-47b4-a111-5ee38d49c5a8.png)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
terra_sdk.exceptions.LCDResponseError: Status 404 - {'code': 5, 'message': 'rpc error: code = NotFound desc = account terra1 not 
found: key not found', 'details': []}

any idea why I get that? Its a real mnemonic and it shows my address in the error response so not sure why there is any error if its finding the account. thanks!

**Comment by RylandCapital** [comment]
![image](https://user-images.githubusercontent.com/16804873/157312937-a363fcdb-9aea-49a2-9e73-fcb12563fa51.png)

got it to work as expected. not sure why first example didnt work but any insight would be great!

**Comment by Vritra4** [comment]
2.0.3 has issues with async client. try 2.0.4 please.

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)
