### ISSUE TITLE
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by RylandCapital** [terra-money/terra.py#87]
terra_sdk version: 2.0.5
Python version: 3.9.4
Operating System: Windows
### Description

I am calling my wallets bank in a python console, and received this error. After reading, I dont quite understand it and thought id reach out for some help. when not using async do I need to be closing a previous connection?

### What I Did
terra = LCDClient(
    "https://lcd.terra.dev", "columbus-5"
    )

  mk = MnemonicKey(
  mnemonic=walletkey
  )
  wallet = client.wallet(mk)
  bank = pd.DataFrame(
      client.bank.balance(wallet.key.acc_address)[0].to_data()
  ).set_index('denom').astype(int)

```
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\rmathews\Desktop\WPy64-3940\python-3.9.4.amd64\lib\asyncio\events.py", line 80, in _run   
    self._context.run(self._callback, *self._args)
  File "C:\Users\rmathews\Desktop\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 162, 
in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

```

**Comment by Aureliano90** [comment]
I don't see anywhere `client` is defined in your code. I have no problem running this.

```
client = LCDClient("https://lcd.terra.dev", "columbus-5")
mk = MnemonicKey(mnemonic=walletkey)
wallet = client.wallet(mk)
bank = client.bank.balance(wallet.key.acc_address)
```

**Comment by robiso50** [comment]
Hello @RylandCapital  , A support ticket has been opened for you with Support ticket number TB7849HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by lopezj19** [comment]
> terra_sdk version: 2.0.5 Python version: 3.9.4 Operating System: Windows
> 
> ### Description
> I am calling my wallets bank in a python console, and received this error. After reading, I dont quite understand it and thought id reach out for some help. when not using async do I need to be closing a previous connection?
> 
> ### What I Did
> terra = LCDClient( "https://lcd.terra.dev", "columbus-5" )
> 
> mk = MnemonicKey( mnemonic=walletkey ) wallet = client.wallet(mk) bank = pd.DataFrame( client.bank.balance(wallet.key.acc_address)[0].to_data() ).set_index('denom').astype(int)
> 
> ```
> Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
> handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
> Traceback (most recent call last):
>   File "C:\Users\rmathews\Desktop\WPy64-3940\python-3.9.4.amd64\lib\asyncio\events.py", line 80, in _run   
>     self._context.run(self._callback, *self._args)
>   File "C:\Users\rmathews\Desktop\WPy64-3940\python-3.9.4.amd64\lib\asyncio\proactor_events.py", line 162, 
> in _call_connection_lost
>     self._sock.shutdown(socket.SHUT_RDWR)
> ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
> ```

Hello @RylandCapital  , A support ticket has been opened for you with Support ticket number TB128363H. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by lopezj19** [comment]
> I don't see anywhere `client` is defined in your code. I have no problem running this.
> 
> ```
> client = LCDClient("https://lcd.terra.dev", "columbus-5")
> mk = MnemonicKey(mnemonic=walletkey)
> wallet = client.wallet(mk)
> bank = client.bank.balance(wallet.key.acc_address)
> ```

Hello @Aureliano90  , A support ticket has been opened for you with Support ticket number TB7926HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by unl1k3ly** [comment]
Dude ... piss off

**Comment by RylandCapital** [comment]
@Aureliano90 I have no issue running it either, "the winError 10054 an existing connection was closed" pops randomly it seems. I can run that code perfectly 9 times out of 10. im assuming this has something to do with my environment. thank you for all your help.
