### ISSUE TITLE
Could not parse Code if -- tx logs are empty

### ISSUE THREAD

**Issue by spaceh3ad** [terra-money/terra.py#88]
- terra_sdk version: 2.0.4
- Python version: Python 3.9.7
- Operating System: Ubuntu 20.04

### Description

I wanted to deploy cw-20 contract to bombay testnet but got this error.
As far as I know it was due to missing sequence in tx but adding this didn't help.

```
sequence = lt.auth.account_info(deployer.key.acc_address).sequence
code_id = 154
contract_address = get_contract_address(instantiate_contract(code_id,
                                                             {
                                                                 "name": "Test Terra Token",
                                                                 "symbol": "TTT",
                                                                 "decimals": 6,
                                                                 "pair_code_id": 155,
                                                                 "token_code_id": 148,
                                                                 "initial_balances": [
                                                                     {"address": deployer.key.acc_address,
                                                                      "amount": "1000000000"}
                                                                 ]
                                                             }, sequence))
```

### What I Did

`python3 deploy_bombay.py`

```
  File "/home/josh/miniconda3/lib/python3.9/site-packages/terra_sdk/util/contract.py", line 70, in get_contract_address
    raise ValueError("could not parse code id -- tx logs are empty.")
ValueError: could not parse code id -- tx logs are empty.
```

**Comment by Vritra4** [comment]
are you sure your instantiate_contract() is returning a BlockTxBroadcastResult?

**Comment by robiso50** [comment]
Hello @spaceh3ad  , A support ticket has been opened for you with Support ticket number TB7848HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by lopezj19** [comment]
> * terra_sdk version: 2.0.4
> * Python version: Python 3.9.7
> * Operating System: Ubuntu 20.04
> 
> ### Description
> I wanted to deploy cw-20 contract to bombay testnet but got this error. As far as I know it was due to missing sequence in tx but adding this didn't help.
> 
> ```
> sequence = lt.auth.account_info(deployer.key.acc_address).sequence
> code_id = 154
> contract_address = get_contract_address(instantiate_contract(code_id,
>                                                              {
>                                                                  "name": "Test Terra Token",
>                                                                  "symbol": "TTT",
>                                                                  "decimals": 6,
>                                                                  "pair_code_id": 155,
>                                                                  "token_code_id": 148,
>                                                                  "initial_balances": [
>                                                                      {"address": deployer.key.acc_address,
>                                                                       "amount": "1000000000"}
>                                                                  ]
>                                                              }, sequence))
> ```
> 
> ### What I Did
> `python3 deploy_bombay.py`
> 
> ```
>   File "/home/josh/miniconda3/lib/python3.9/site-packages/terra_sdk/util/contract.py", line 70, in get_contract_address
>     raise ValueError("could not parse code id -- tx logs are empty.")
> ValueError: could not parse code id -- tx logs are empty.
> ```

Hello, A support ticket has been opened for you with Support ticket number TM7373. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by Vritra4** [comment]
@spaceh3ad feel free to reopen this issue if you still have a problem.
