### ISSUE TITLE
Exception on module LCDClient().gov.proposals for ProposalStatus(2)

### ISSUE THREAD

**Issue by Jackson-DKMG** [terra-money/terra.py#90]
- terra_sdk version: 2.0.4 & 2.0.5
- Python version: 3.8 & 3.9
- Operating System: Ubuntu 20.04 & 21.04

### Description

Trying to get the Terra proposals in voting period, which was working until a few days ago and now generates an exception.

Importantly, the same command for proposals in other stages works fine : DEPOSIT_PERIOD, PASSED, REJECTED.

### What I Did

```
from terra_sdk.client.lcd import LCDClient
from terra_sdk.core.gov import ProposalStatus
terra = LCDClient(chain_id="columbus-5", url="https://lcd.terra.dev")
proposals = terra.gov.proposals({"proposal_status": ProposalStatus(2)})
```
It returns:

```
content type is invalid
```

However, ```terra.gov.proposals({"proposal_status": ProposalStatus(0)})``` for example returns the expected object containing the proposals. (same with 1, 3, 4 for the different stages).

**Comment by Vritra4** [comment]
it's already known problem and fixed but not released yet. :( i'll release it soon with other updates.
thanks for reporting anyway :)

**Comment by Jackson-DKMG** [comment]
oh, I didn't see it, my apologies then, and looking forward to the release :)

**Comment by Vritra4** [comment]
try v2.0.6 :)
