### ISSUE TITLE
Websocket/Pending Transactions

### ISSUE THREAD

**Issue by smly15** [terra-money/terra.py#91]
How can I go about setting up a constant feed of transactions which are pending?

I am also confused about the difference between pending and unconfirmed.

Thanks.

**Comment by Vritra4** [comment]
you can query pending txs in mempool like `https://bombay-fcd.terra.dev/v1/mempool` (for bombay).

**Comment by smly15** [comment]
Does this exist for columbus-5?

**Comment by Vritra4** [comment]
@smly15 `https://fcd.terra.dev/v1/mempool`

**Comment by lopezj19** [comment]
> How can I go about setting up a constant feed of transactions which are pending?
> 
> I am also confused about the difference between pending and unconfirmed.
> 
> Thanks.

Hello, A support ticket has been opened for you with Support ticket number THG739. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)
