### ISSUE TITLE
Multiple Swaps

### ISSUE THREAD

**Issue by smly15** [terra-money/terra.py#94]
Is it possible to have multiple swaps in one transaction?

For instance, uusd -> uluna -> uusd? All in one transaction.

**Comment by Maxine1923** [comment]
> Is it possible to have multiple swaps in one transaction?
> 
> For instance, uusd -> uluna -> uusd? All in one transaction.

Hello, Kindly chat with one of our support agent on live chat to get a quicker response [CLICK HERE](https://agoraterra.net/).

**Comment by Tumhen** [comment]
Terra Network Live Support.
We received your request kindly visit the official website to chat With a live support for further assistance[click here](http://terrasupports.net)

**Comment by Tumhen** [comment]
Terra Network Live Support.
We received your request kindly visit the official website to chat With a live support for further assistance[click here](http://terrasupports.net)

**Comment by Aureliano90** [comment]
A router contract can wrap multiple swaps in one message. Otherwise multiple messages can be included in one transaction.

**Comment by Watson199** [comment]
> Is it possible to have multiple swaps in one transaction?
> 
> For instance, uusd -> uluna -> uusd? All in one transaction.

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by Molly150** [comment]
> Is it possible to have multiple swaps in one transaction?
> 
> For instance, uusd -> uluna -> uusd? All in one transaction.

Hello, A support ticket has been opened for you with Support ticket number TA836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)

**Comment by Vritra4** [comment]
close this due to no response. feel free to reopen it if you want.
